### PR TITLE
Init sub-projects, so their plugins are applied

### PR DESCRIPTION
**Pull request by hugoduncan**
Their could be a potential problem with this if the plugins provide hooks, as the hooks will not be cleared between sub-projects.

@technomancy - this is what I would like to have scoped hooks to support. Hence https://github.com/technomancy/robert-hooke/pull/10

### CODE REVIEW

**Comment by kumarshantanu** [comment]
Addressing @hugoduncan just in case you missed the notification. :)

**Comment by hugoduncan** [comment]
I can't reproduce the issue. I have seen that error message before though, but can't remember what the context was. Which version of lein are you testing with?

**Comment by kumarshantanu** [comment]
I am running `Leiningen 2.0.0-preview10 on Java 1.7.0_07 Java HotSpot(TM) Client VM` on 32-bit Linux.

**Comment by hugoduncan** [comment]
I'm afraid I still can't provoke the error. Is this on a publicly available project? Does lein work correctly when invoked directly in the sub-project?

Maybe you could gist the exception. Looking at the leiningen code, l.c.classpath/resolve-dependencies is called with `:add-classpath? true` from l.c.project/load-plugins, and calls l.c.lasspath/get-dependencies passing the `:add-classpath` in it's rest argument. Nothing jumps out as being wrong there.

**Comment by kumarshantanu** [comment]
I have added the `subtest` project that I was using to test `lein-sub` to this repo master. Individual `lein clean`, `lein jar` etc work fine on the _child_ projects, but `lein sub clean` from within `subtest` produces the error I mentioned earlier.

**Comment by hugoduncan** [comment]
I'm afraid I can't reproduce this on my machine (OS X 10.7.4).

I did `lein do clean, install` in a clean checkout of master, and `lein sub clean` works from within `subtest` with lein preview 7 through preview 10, and with master. I've commented out the whole of my `~/.lein/profiles.clj` while testing.

I have also tested on a clean Ubuntu 12.04 vm, with the same result.

**Comment by kumarshantanu** [comment]
@hugoduncan Sorry to waste your time, the issue was with `lein-pedantic 0.0.3` https://github.com/xeqi/lein-pedantic in my `profiles.clj` file. Maybe @xeqi would know what's up. I have pushed a `0.2.3` release to Clojars and updated the README.

**Comment by hugoduncan** [comment]
Glad to hear you found a cause. Thanks for the release!

**Comment by xeqi** [comment]
Hmm, lein-pedantic does hooke that area to check dependencies.  Made an issue to track/explore it in lein-pedantic.

**Pull request merged**
